
//GET

###
GET http://localhost:3000/api/travels

//POST

###
POST http://localhost:3000/api/travels
Content-Type: application/json

{
   "departure_date":,
   "arrival_date":,
   "departure_id":,
   "arrival_id":
   }

//
