
//GET

###
GET http://localhost:3000/api/clients

###
GET http://localhost:3000/api/clients
//POST

###
POST http://localhost:3000/api/clients
Content-Type: application/json

{
    "name": "",
    "surname": "",
    "address":"", 
    "phone":, 
    "birth":"", 
    "email":"", 
    "dni":""
    }

//PUT

PUT http://localhost:3000/api/clients/3
Content-Type: application/json

{
    "name": "",
    "surname": "",
    "address":"", 
    "phone":, 
    "birth":"", 
    "email":"", 
    "dni":"",
    "role":
    }
