
###
GET http://localhost:3000/api/clients

###
POST http://localhost:3000/api/clients
Content-Type: application/json

{
    "name": "Miquel",
    "surname": "Abella",
    "address":"c/pato,23 Barcelona", 
    "phone":78965458, 
    "birth":"1988-10-20", 
    "email":"mab@gmail.com", 
    "dni":"5554698E"
    }